// GENERATED by scripts/build-data.js. Do not edit by hand.
// Served only through the signed-in /api/members route. Never import from src/.
export default {
  "generatedAt": "2026-09-04T14:01:45.929Z",
  "members": [
    {
      "name": "Aurimas Baciauskas",
      "status": "Active",
      "aliases": [
        "Auri"
      ],
      "attended": 7
    },
    {
      "name": "Aiza Watzlawek",
      "status": "Active",
      "aliases": [],
      "attended": 3
    },
    {
      "name": "Andrei Prusu",
      "status": "Active",
      "aliases": [],
      "attended": 2
    },
    {
      "name": "Cristina Bodnari",
      "status": "Active",
      "aliases": [],
      "attended": 1
    },
    {
      "name": "Dovile",
      "status": "Active",
      "aliases": [
        "Dovile Perednyte"
      ],
      "attended": 1
    },
    {
      "name": "Dovydas Vinickis",
      "status": "Active",
      "aliases": [],
      "attended": 0
    },
    {
      "name": "Eividas Maciulis",
      "status": "Active",
      "aliases": [],
      "attended": 5
    },
    {
      "name": "Ernestas Sažinas",
      "status": "Active",
      "aliases": [
        "Ernestas"
      ],
      "attended": 0
    },
    {
      "name": "Ignas Valavicius",
      "status": "Active",
      "aliases": [],
      "attended": 7
    },
    {
      "name": "Inigo Casillas",
      "status": "Active",
      "aliases": [
        "Inigo"
      ],
      "attended": 0
    },
    {
      "name": "Justas Petrauskas",
      "status": "Active",
      "aliases": [],
      "attended": 1
    },
    {
      "name": "Kernius Savickas",
      "status": "Active",
      "aliases": [
        "Kernius"
      ],
      "attended": 0
    },
    {
      "name": "Kristina Juozapaviciute",
      "status": "Active",
      "aliases": [
        "Kristina"
      ],
      "attended": 0
    },
    {
      "name": "Maria Krupa",
      "status": "Active",
      "aliases": [
        "Maria"
      ],
      "attended": 0
    },
    {
      "name": "Marlu Adamczyk",
      "status": "Active",
      "aliases": [
        "Marlu"
      ],
      "attended": 0
    },
    {
      "name": "Martin Windsor",
      "status": "Active",
      "aliases": [],
      "attended": 1
    },
    {
      "name": "Pavel Kucera",
      "status": "Active",
      "aliases": [
        "Pavel"
      ],
      "attended": 0
    },
    {
      "name": "Prachi Abhyankar",
      "status": "Active",
      "aliases": [
        "Prachi"
      ],
      "attended": 0
    },
    {
      "name": "Roman Novosad",
      "status": "Active",
      "aliases": [],
      "attended": 1
    },
    {
      "name": "Sany Ivanova",
      "status": "Active",
      "aliases": [],
      "attended": 6
    },
    {
      "name": "Tady Kapic",
      "status": "Active",
      "aliases": [],
      "attended": 1
    },
    {
      "name": "Valentin",
      "status": "Active",
      "aliases": [],
      "attended": 1
    },
    {
      "name": "Vasare Liutkeviciute",
      "status": "Active",
      "aliases": [
        "Vasare"
      ],
      "attended": 0
    }
  ],
  "profiles": {
    "Aurimas Baciauskas": {
      "linkedin": "https://www.linkedin.com/in/auribaci/",
      "photo": "/members/auri.png",
      "order": 1
    },
    "Eividas Maciulis": {
      "linkedin": "https://www.linkedin.com/in/eividas-m/",
      "photo": "/members/eividas.jpg",
      "order": 2
    },
    "Ignas Valavicius": {
      "linkedin": "https://www.linkedin.com/in/valavicius/",
      "photo": "/members/ignas.jpg"
    },
    "Andrei Prusu": {
      "photo": "/members/andrei.jpg"
    },
    "Dovydas Vinickis": {
      "linkedin": "https://dk.linkedin.com/in/dovydas-vinickis",
      "photo": "/members/dovydas.jpg"
    },
    "Sany Ivanova": {
      "linkedin": "https://www.linkedin.com/in/sany-ivanova-307373120/",
      "photo": "/members/sany.jpg"
    },
    "Martin Windsor": {
      "linkedin": "https://www.linkedin.com/in/martin-windsor/",
      "photo": "/members/martin.jpg"
    },
    "Justas Petrauskas": {
      "linkedin": "https://www.linkedin.com/in/petrauskasjustas/",
      "photo": "/members/justas.jpg",
      "linkedinBug": "black"
    },
    "Pavel Kucera": {
      "linkedin": "https://www.linkedin.com/in/pavelkucera-cph/",
      "photo": "/members/pavel.jpg"
    },
    "Ernestas Sažinas": {
      "linkedin": "https://www.linkedin.com/in/ernestas-sazinas/",
      "photo": "/members/ernestas.jpg",
      "linkedinBug": "black"
    },
    "Dovile": {
      "displayName": "Dovile Perednyte",
      "linkedin": "https://www.linkedin.com/in/dovile-perednyte/",
      "photo": "/members/dovile.jpg"
    },
    "Roman Novosad": {
      "linkedin": "https://www.linkedin.com/in/roman-novosad/",
      "photo": "/members/roman.jpg"
    },
    "Marlu Adamczyk": {
      "linkedin": "https://www.linkedin.com/in/marlu/",
      "photo": "/members/marlu.jpg"
    },
    "Prachi Abhyankar": {
      "linkedin": "https://www.linkedin.com/in/prachiabhyankar/",
      "photo": "/members/prachi.jpg"
    },
    "Maria Krupa": {
      "linkedin": "https://www.linkedin.com/in/maria-krupa-/",
      "photo": "/members/maria.jpg",
      "order": 99
    },
    "Inigo Casillas": {
      "gender": "male"
    },
    "Aiza Watzlawek": {
      "linkedin": "https://www.linkedin.com/in/aiza-a-watzlawek/",
      "photo": "/members/aiza.jpg"
    },
    "Cristina Bodnari": {
      "gender": "female"
    },
    "Kernius Savickas": {
      "gender": "male"
    },
    "Kristina Juozapaviciute": {
      "gender": "female"
    },
    "Vasare Liutkeviciute": {
      "gender": "female"
    },
    "Tady Kapic": {
      "gender": "male"
    },
    "Valentin": {
      "gender": "male"
    }
  },
  "attendeesByDate": {
    "2025-06-29": [
      "Auri",
      "Ignas",
      "Sany",
      "Aiza"
    ],
    "2025-07-12": [
      "Auri",
      "Ignas",
      "Sany",
      "Aiza",
      "Eividas",
      "Valentin",
      "Mari"
    ],
    "2025-07-27": [
      "Auri",
      "Ignas",
      "Sany",
      "Eividas",
      "Dovile"
    ],
    "2025-09-14": [
      "Auri",
      "Eividas",
      "Ignas",
      "Martin",
      "Tady",
      "Cristina"
    ],
    "2026-03-08": [],
    "2026-05-03": [],
    "2026-05-31": [
      "Auri",
      "Yogi",
      "Eividas",
      "Justas",
      "Sany",
      "Frederik",
      "Ignas"
    ],
    "2026-06-14": [
      "Auri",
      "Andrei",
      "Sany",
      "Eividas",
      "Ignas"
    ],
    "2026-08-30": [
      "Auri",
      "Ignas",
      "Sany",
      "Andrei",
      "Aiza",
      "Roman"
    ]
  }
};
