// GENERATED by scripts/build-data.js. Do not edit by hand.
// The allowed targets for a photo move (/api/photos PATCH). Never import from src/.
export const SESSION_DATES = [
  "2025-06-29",
  "2025-07-12",
  "2025-07-27",
  "2025-09-14",
  "2026-03-08",
  "2026-05-03",
  "2026-05-17",
  "2026-05-31",
  "2026-06-14",
  "2026-06-28",
  "2026-07-12",
  "2026-08-30"
];
